export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG'

export const CHANGE_PLAY_LIST = 'player/CHANGE_PLAY_LIST'
export const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX'

export const CHANGE_SEQUENCE = 'player/CHANGE_SEQUENCE'

export const CHANGE_PLAY_LYRICS = 'player/CHANGE_PLAY_LYRICS'
export const CHANGE_PAGES_LYRICS = 'player/CHANGE_PAGES_LYRICS'

export const CHANGE_LYRICS_INDEX = 'player/CHANGE_LYRICS_INDEX'

export const CHANGE_ONPLAYING = 'player/CHANGE_ONPLAYING'

export const CHANGE_MASK_COVER = 'player/CHANGE_MASK_COVER'

export const CHANGE_OPEN = 'player/CHANGE_OPEN'
