export const CHANGE_ALL_SONG_LIST = 'ranking/CHANGE_ALL_SONG_LIST'

export const CHANGE_SONG_LIST_DETAIL = 'ranking/CHANGE_SONG_LIST_DETAIL'

export const CHANGE_SONG_LIST_TITLE = 'ranking/CHANGE_SONG_LIST_TITLE' 